---
title: "Gene expression for one sample [Normalized]"
author: "ATIA Safiya"
date: "2023-07-26"
params:
  samp: "samp"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    number_sections: true
    theme: lumen
---

# Seurat object  
## Load required packages
```{r,  message=FALSE, warning=FALSE}
library(Seurat)
library(tidyverse)
library(ggplot2)
library('enrichR')

## annotation
library("SCINA")

library("viridis")
```

## Load seurat object (NORM)
```{r}
samp <- params$samp
```

```{r}
seurat_obj <- readRDS(file = paste0('./Lucille/results/rds/samples/', samp, '_Clusters.rds'))

seurat_obj
table(seurat_obj$orig.ident)
```

## Load seurat object (metabo) 
```{r}
metabo_obj <- readRDS(file = paste0('./Lucille/results/rds/samples/', samp, '_Clusters_metabo.rds'))

metabo_obj
table(metabo_obj$orig.ident)
```

# Expression
```{r}
FeaturePlot(seurat_obj, features = c("SOX9", "OLIG1"))
FeaturePlot(metabo_obj, features = c("SOX9", "OLIG1"))
```

```{r}
FeaturePlot(seurat_obj, features = c("APOE", "KCNN3", "CRYAB", "ID4"))
FeaturePlot(metabo_obj, features = c("APOE", "KCNN3", "CRYAB", "ID4"))
```

```{r}
FeaturePlot(seurat_obj, features = c("PDGFRA", "SOX8", "SOX4", "ASCL1"))
FeaturePlot(metabo_obj, features = c("PDGFRA", "SOX8", "SOX4", "ASCL1"))
```