---
title: "Previous plots for one sample [Normalized]"
author: "ATIA Safiya"
date: "2023-07-26"
params:
  sample: "sample"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    number_sections: true
    theme: lumen
---

# Seurat object  
## Load required packages
```{r,  message=FALSE, warning=FALSE}
library(Seurat)
library(tidyverse)
library(ggplot2)
library(viridis)
```

## Load seurat object (NORM)
```{r}
sample <- params$sample
line = str_split_1(sample, '_')[1]

seurat_obj <- readRDS(file = paste0('./results/rds/samples/norm_', sample, '.rds'))

seurat_obj
table(seurat_obj$orig.ident)
```

# PCA
```{r, warning=FALSE}
DimPlot(seurat_obj, reduction = "pca", group.by = "orig.ident")
DimPlot(seurat_obj, reduction = "pca", group.by = "orig.ident", label.size = 4, label = TRUE)+ NoLegend()

DimPlot(seurat_obj, reduction = "pca", group.by = "Phase", cols = c(G1='azure4',G2M='dodgerblue', S='tomato3') )
```

# Clusters 

```{r, warning=FALSE}
DimPlot(seurat_obj, reduction = "umap", group.by = "orig.ident")
DimPlot(seurat_obj, reduction = "umap", group.by = "orig.ident", label.size = 4, label = TRUE)+ NoLegend()

DimPlot(seurat_obj, reduction = "umap", group.by = "Phase", cols = c(G1='azure4',G2M='dodgerblue', S='tomato3') )
```

# Annotation
## Oligo/Astro
```{r}
colors <- c(astro='seagreen4', oligo_progenitors = "#297fb8" ,mature_oligo='orangered3', unknown="lightgray")

DimPlot(seurat_obj, reduction = "umap",  group.by = "scina_labels", cols = colors)
DimPlot(seurat_obj, reduction = "tsne",  group.by = "scina_labels", cols = colors)
```

## Panglao  
### UMAP  
```{r}
nb <- length(unique(seurat_obj$brain_signatures_prediction))

DimPlot(seurat_obj, reduction = "umap", group.by = "brain_signatures_prediction", cols= c(viridis(nb-1),"gray")) + NoLegend()

## see the legend
DimPlot(seurat_obj, reduction = "umap", group.by = "brain_signatures_prediction", label.size = 4, label = TRUE, cols= c(viridis(nb-1),"gray")) + NoLegend()
DimPlot(seurat_obj, reduction = "umap",  group.by = "brain_signatures_prediction", cols= c(viridis(nb-1),"gray"))
```


### tSNE  
```{r}
DimPlot(seurat_obj, reduction = "tsne", group.by = "brain_signatures_prediction", cols= c(viridis(nb-1),"gray")) + NoLegend()

## see the legend
DimPlot(seurat_obj, reduction = "tsne", group.by = "brain_signatures_prediction", label.size = 4, label = TRUE, cols= c(viridis(nb-1),"gray")) + NoLegend()
DimPlot(seurat_obj, reduction = "tsne",  group.by = "brain_signatures_prediction", cols= c(viridis(nb-1),"gray"))
```
