---
title: "Heatmap [Normalized]"
author: "Safiya ATIA"
date: "2023-07-27"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    number_sections: true
    theme: lumen
---

# Seurat object  
## Load required packages
```{r,  message=FALSE, warning=FALSE}
library(Seurat)
library(tidyverse)
library(ggplot2)

library("viridis")
```

## Load seurat object (NORM)

```{r}
seurat_obj <- readRDS(file = './results/rds/all_samples_Clusters.rds')

seurat_obj
table(seurat_obj$orig.ident)
```

```{r}
all_markers <- readRDS(file = './results/html/all_samples_cluster.markers.rds')

dim(all_markers)
```

## Load seurat object (METABO)
```{r}
metabo_obj <- readRDS(file = './results/rds/all_samples_Clusters_metabo.rds')

metabo_obj
table(metabo_obj$orig.ident)
```

```{r}
metabo_markers <- readRDS(file = './results/html/all_samples_cluster.markers_metabo.rds')

dim(metabo_markers)
```


# Heatmap
## all genes
```{r}
prolif <- all_markers[which( all_markers$diff_p_val == all_markers$max_pval), ]
dim(prolif)
prolif <- prolif[, c('prolif_p_val', 'prolif_avg_log2FC', 'prolif_p_val_adj', 'gene', 'cluster' )]
head(prolif)


diff <- all_markers[which( all_markers$prolif_p_val == all_markers$max_pval), ]
dim(diff)
diff <- diff[, c('diff_p_val', 'diff_avg_log2FC', 'diff_p_val_adj', 'gene', 'cluster' )]
head(diff)
```

```{r}
diff_markers <- diff[order(diff$diff_p_val_adj, decreasing = FALSE),]
prolif_markers <- prolif[order(prolif$prolif_p_val_adj, decreasing = FALSE),]
```

### diff
```{r}
diff_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = diff_avg_log2FC) -> top10

DoHeatmap(subset(seurat_obj, subset = seurat_clusters %in% c(0,1,2)), 
          features = top10$gene) + theme(axis.text=element_text(size=3)) + NoLegend()
```

```{r}
diff_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = diff_avg_log2FC) -> top10

DoHeatmap(subset(seurat_obj, subset = seurat_clusters %in% c(3,4,5)), 
          features = top10$gene) + theme(axis.text=element_text(size=3)) + NoLegend()
```

```{r}
diff_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = diff_avg_log2FC) -> top10

DoHeatmap(subset(seurat_obj, subset = seurat_clusters %in% c(6,7,8,9,10)), 
          features = top10$gene) + theme(axis.text=element_text(size=3)) + NoLegend()
```

```{r}
diff_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = diff_avg_log2FC) -> top10

DoHeatmap(subset(seurat_obj, subset = seurat_clusters %in% c(11,12,13,14)), 
          features = top10$gene) + theme(axis.text=element_text(size=3)) + NoLegend()
```

```{r}
diff_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = diff_avg_log2FC) -> top10

DoHeatmap(subset(seurat_obj, subset = seurat_clusters %in% c(15,16,17)), 
          features = top10$gene) + theme(axis.text=element_text(size=3)) + NoLegend()
```


### prolif
```{r}
prolif_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = prolif_avg_log2FC) -> top10

DoHeatmap(subset(seurat_obj, subset = seurat_clusters %in% c(0,1,2)), 
          features = top10$gene) + theme(axis.text=element_text(size=3)) + NoLegend()
```

```{r}
prolif_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = prolif_avg_log2FC) -> top10

DoHeatmap(subset(seurat_obj, subset = seurat_clusters %in% c(3,4,5)), 
          features = top10$gene) + theme(axis.text=element_text(size=3)) + NoLegend()
```

```{r}
prolif_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = prolif_avg_log2FC) -> top10

DoHeatmap(subset(seurat_obj, subset = seurat_clusters %in% c(6,7,8,9,10)), 
          features = top10$gene) + theme(axis.text=element_text(size=3)) + NoLegend()
```

```{r}
prolif_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = prolif_avg_log2FC) -> top10

DoHeatmap(subset(seurat_obj, subset = seurat_clusters %in% c(11,12,13,14)), 
          features = top10$gene) + theme(axis.text=element_text(size=3)) + NoLegend()
```

```{r}
prolif_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = prolif_avg_log2FC) -> top10

DoHeatmap(subset(seurat_obj, subset = seurat_clusters %in% c(15,16,17)), 
          features = top10$gene) + theme(axis.text=element_text(size=3)) + NoLegend()
```


## metabo genes
```{r}
prolif <- metabo_markers[which( metabo_markers$diff_p_val == metabo_markers$max_pval), ]
dim(prolif)
prolif <- prolif[, c('prolif_p_val', 'prolif_avg_log2FC', 'prolif_p_val_adj', 'gene', 'cluster' )]
head(prolif)


diff <- metabo_markers[which( metabo_markers$prolif_p_val == metabo_markers$max_pval), ]
dim(diff)
diff <- diff[, c('diff_p_val', 'diff_avg_log2FC', 'diff_p_val_adj', 'gene', 'cluster' )]
head(diff)
```

```{r}
diff_markers <- diff[order(diff$diff_p_val_adj, decreasing = FALSE),]
prolif_markers <- prolif[order(prolif$prolif_p_val_adj, decreasing = FALSE),]
```

### diff
```{r}
diff_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = diff_avg_log2FC) -> top10

DoHeatmap(subset(metabo_obj, subset = seurat_clusters %in% c(0,1)), 
          features = top10$gene) + theme(axis.text=element_text(size=4)) + NoLegend()
```

```{r}
diff_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = diff_avg_log2FC) -> top10

DoHeatmap(subset(metabo_obj, subset = seurat_clusters %in% c(2,3,4)), 
          features = top10$gene) + theme(axis.text=element_text(size=4)) + NoLegend()
```

```{r}
diff_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = diff_avg_log2FC) -> top10

DoHeatmap(subset(metabo_obj, subset = seurat_clusters %in% c(5,6,7)), 
          features = top10$gene) + theme(axis.text=element_text(size=4)) + NoLegend()
```

```{r}
diff_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = diff_avg_log2FC) -> top10

DoHeatmap(subset(metabo_obj, subset = seurat_clusters %in% c(8,9,10)), 
          features = top10$gene) + theme(axis.text=element_text(size=4)) + NoLegend()
```


### prolif
```{r}
prolif_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = prolif_avg_log2FC) -> top10

DoHeatmap(subset(metabo_obj, subset = seurat_clusters %in% c(0,1)), 
          features = top10$gene) + theme(axis.text=element_text(size=4)) + NoLegend()
```

```{r}
prolif_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = prolif_avg_log2FC) -> top10

DoHeatmap(subset(metabo_obj, subset = seurat_clusters %in% c(2,3,4)), 
          features = top10$gene) + theme(axis.text=element_text(size=4)) + NoLegend()
```

```{r}
prolif_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = prolif_avg_log2FC) -> top10

DoHeatmap(subset(metabo_obj, subset = seurat_clusters %in% c(5,6,7)), 
          features = top10$gene) + theme(axis.text=element_text(size=4)) + NoLegend()
```

```{r}
prolif_markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = prolif_avg_log2FC) -> top10

DoHeatmap(subset(metabo_obj, subset = seurat_clusters %in% c(8,9,10)), 
          features = top10$gene) + theme(axis.text=element_text(size=4)) + NoLegend()
```