---
title: "Buk RNAseq analysis [Airelle's data]"
author: "ATIA Safiya"
date: "2023-06-26"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    number_sections: true
    theme: lumen
---

# Environment
## Load required packages
```{r,  message=FALSE, warning=FALSE}
## Graphics plots
library(FactoMineR)
library(ggplot2)

## Differential analysis
library(edgeR)
library(limma)

## General data manipulation
library(tidyr)
library(dplyr)

library(DESeq2)
library(stringr)
library(tximport)

library(PoiClaClu)
library(RColorBrewer)
library(pheatmap)
```

## Load data
```{r}
txi <- readRDS("txi.rds")
colnames(txi$counts) <- str_sub(colnames(txi$counts), end = -6)
dim(txi$counts)
```

# Design
```{r}
## experimental design
nb <- c(rep(5,6),4,4,7,6,6,rep(5,5))
geno <- rep(c("DKO_E4F1_MDM2","DKO_E4F1_P53","DKO_MDM2_P53", "SKO_E4F1","SKO_MDM2","SKO_P53","TKO", "WT"), each=2)
genotype <- rep(geno, nb)

cond <- rep(c("Fasted","Fed"),8)
condition <- rep(cond, nb)
expdes <- data.frame(genotype, condition)
rownames(expdes) <- colnames(txi$counts)

expdes$genotype <- as.factor(expdes$genotype)
expdes$condition <- as.factor(expdes$condition)

## put WT and Fed as the reference level
expdes$genotype = relevel( expdes$genotype, "WT")
expdes$condition = relevel( expdes$condition, "Fed")

head(expdes)
dim(expdes)
```
